name = "purple-river-0717"
main = "worker.js"
compatibility_date = "2024-01-01"
account_id = "0f644373a9db40f2b36e4ffece348c46"
keep_vars = true

[env.production]
vars = { }

# 환경 변수는 Cloudflare Dashboard에서 설정:
# SUPABASE_URL
# SUPABASE_SERVICE_ROLE_KEY
